name: documentation

on: [pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install -r docs/requirements-docs.txt
      - name: Sphinx build
        working-directory: ./docs
        run: |
          make clean
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        # this command only run on push to main
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html/
          force_orphan: true
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   # if the branch is not main, deploy to a branch with the same name
      #   if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
      #   with:
      #     publish_branch: ${{ github.ref }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: _build/
      #     force_orphan: true