# This workflow will upload a Python Package using Poetry
name: Upload Python Package

on:
  release:
    types: [prereleased]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Poetry create test pypi
      run: |
        poetry config.repositories.test-pypi https://test.pypi.org
        poetry config pypi-token.test-pypi ${{ secrets.PYPI_TEST_TOKEN }}

    - name: Build
      run: poetry build
    
    - name: Publish test-pypi
      run: poetry publish -r test-pypi
